{{- /*
Copyright 2025 SUSE LLC
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if and .Values.mcpo.ingress.enabled .Values.mcpo.enabled .Values.mcpo.ingress.enabled -}}
{{- $fullName := include "trento-mcp-server.fullname" . -}}
{{- $svcPort := .Values.mcpo.port -}}
{{- if and .Values.mcpo.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.mcpo.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.mcpo.ingress.annotations "kubernetes.io/ingress.class" .Values.mcpo.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-mcpo
  labels:
    {{- include "trento-mcp-server.labels" . | nindent 4 }}
  {{- with .Values.mcpo.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if eq $.Values.mcpo.ingress.className "traefik" }}
    # This middleware strips the prefix from the request path
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-{{ include "trento-mcp-server.fullname" $ }}-mcpo-strip-prefix@kubernetescrd
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.mcpo.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.mcpo.ingress.className }}
  {{- end }}
  {{- if .Values.mcpo.ingress.tls }}
  tls:
    {{- range .Values.mcpo.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mcpo.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
