# Copyright 2025 SUSE LLC
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "trento-mcp-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: trento-mcp-server
  {{- include "trento-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mcpServer.type }}
  selector:
    app: trento-mcp-server
    {{- include "trento-mcp-server.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mcpServer.ports | toYaml | nindent 2 }}
