{{- /*
Copyright 2025 SUSE LLC
SPDX-License-Identifier: Apache-2.0
*/}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trento-mcp-server.fullname" . }}
  labels:
    {{- include "trento-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: {{ include "trento-mcp-server.port" . }}
      protocol: TCP
      port: {{ include "trento-mcp-server.port" . }}
  selector:
    {{- include "trento-mcp-server.selectorLabels" . | nindent 4 }}
