ifndef::site-gen-antora[:relfileprefix: docs/]
= Trento Helm Charts

Helm charts to deploy Trento components in a Kubernetes cluster.

== Usage

link:https://helm.sh[Helm] must be installed to use the charts. Please refer
to Helm’s link:https://helm.sh/docs/[documentation] to get started.

After that, refer to each individual chart documentation to find more
information:

* xref:trento-server.adoc[trento-server]: Chart to deploy a fully
functional Trento server, including the Web and Wanda components, plus
other auxiliary services (such as the Trento MCP Server).

=== Optional: SSL with cert-manager

link:https://cert-manager.io/[cert-manager] is a Kubernetes add-on that
automates the management and issuance of TLS certificates. It can be
optionally enabled in this Helm chart to provide SSL support for secure
communication. While it simplifies certificate management and renewal,
it introduces additional cluster-wide resources. For detailed setup
instructions and considerations, refer to the
xref:cert-manager.adoc[`+docs/cert-manager/+`] cookbook.

=== Optional: mTLS authentication with RabbitMQ

mTLS authentication with RabbitMQ can be enabled through the
`+global.rabbitmq.tls.mtls.enabled+` flag. If enabled, the chart will take
care of generating the needed certificates (using `+cert-manager+`) and
configuring server and client applications accordingly.

== Support

Please only report bugs via
link:https://github.com/trento-project/trento/issues[GitHub issues]; for any
other inquiry or topic use
link:https://github.com/trento-project/trento/discussions[GitHub discussion].

== Contributing

ifdef::site-gen-antora[]
See xref:CONTRIBUTING.adoc[contribution guidelines].
endif::[]
ifndef::site-gen-antora[]
See link:CONTRIBUTING.adoc[contribution guidelines].
endif::[]

== License

See the LICENSE notice.
