apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trento-certificate
  namespace: ${TRENTO_NAMESPACE}

spec:
  secretName: trento-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

  commonName: ${TRENTO_WEB_ORIGIN}
  dnsNames:
  - ${TRENTO_WEB_ORIGIN}
