trento-web:
  ingress:
    hosts:
        # Adjust this to your FQDN
      - host: demo.trento-project.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: trento-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production

trento-wanda:
  ingress:
    hosts:
      # Adjust this to your FQDN
      - host: demo.trento-project.io
        paths:
        - path: /api/checks
          pathType: ImplementationSpecific
        - path: /api/v1/checks
          pathType: ImplementationSpecific
        - path: /api/v2/checks
          pathType: ImplementationSpecific
        - path: /api/v3/checks
          pathType: ImplementationSpecific
    tls:
      - secretName: trento-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
