{{- if .Values.prometheus.enabled -}}
{{- if eq .Values.prometheus.server.auth.type "basic" -}}
apiVersion: v1
kind: Secret
metadata:
  name: trento-prometheus-auth-htpasswd
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  htpasswd: {{ htpasswd .Values.prometheus.server.auth.basic.username .Values.prometheus.server.auth.basic.password | quote }}
{{- end }}
{{- end }}
