apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: "http_sd_hosts"
        honor_timestamps: true
        scrape_interval: 30s
        scrape_timeout: 30s
        scheme: http
        follow_redirects: true
        http_sd_configs:
        - follow_redirects: true
          refresh_interval: 1m
          url: http://{{ .Release.Name }}-{{ .Values.global.trentoWeb.name }}:{{ .Values.global.trentoWeb.servicePort }}/api/prometheus/targets
