{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: trento-prometheus-web-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  web-config.yml: |
    {{- if eq .Values.prometheus.server.auth.type "basic" }}
    basic_auth_users:
      {{ .Values.prometheus.server.auth.basic.username }}: {{ htpasswd .Values.prometheus.server.auth.basic.username .Values.prometheus.server.auth.basic.password | splitList ":" | last | trim }}
    {{- end }}
{{- end }}
