apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-provision-wanda-database-job"
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          command:
            - sh
            - -c
            - >
              while ! pg_isready -U {{ .Values.global.postgresql.postgresqlUsername }} -h {{ .Release.Name }}-{{ .Values.global.postgresql.name }};
              do sleep 1;
              done;
              echo $COMMAND | psql --file=- --echo-queries --set ON_ERROR_STOP=1
          env:
            - name: PGUSER
              value: "{{ .Values.global.postgresql.postgresqlUsername }}"
            - name: PGPASSWORD
              value: "{{ .Values.global.postgresql.postgresqlPassword }}"
            - name: PGHOST
              value: "{{ .Release.Name }}-{{ .Values.global.postgresql.name }}"
            - name: COMMAND
              value: |
                SELECT 'CREATE DATABASE trento_wanda'
                WHERE NOT EXISTS (
                  SELECT FROM pg_database WHERE datname = 'trento_wanda'
                )
                \gexec
      restartPolicy: OnFailure
  backoffLimit: 4
