apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trento-wanda.fullname" . }}-configmap
data:
  DATABASE_URL: "ecto://{{ .Values.global.postgresql.postgresqlUsername }}:{{ .Values.global.postgresql.postgresqlPassword }}@{{ .Release.Name }}-{{ .Values.global.postgresql.name }}/trento_wanda"
  AMQP_URL: "amqp://trento:trento@{{ .Release.Name }}-{{ .Values.global.rabbitmq.name }}:{{ .Values.global.rabbitmq.servicePort }}"
  CORS_ENABLED: {{ .Values.cors.enabled | quote }}
  {{- if .Values.cors.enabled }}
  CORS_ORIGIN: {{ include "trentoWanda.cors_origin" . | quote }}
  {{- end }}
  OAS_SERVER_URL: "https://{{ .Values.global.trentoWeb.origin }}/wanda"
  {{- $webService := printf "%s-%s.%s.svc.%s" .Release.Name .Values.global.trentoWeb.name .Release.Namespace .Values.global.clusterDomain }}
  {{- $webPort := .Values.global.trentoWeb.servicePort | int }}
  AUTH_SERVER_URL: {{ printf "http://%s:%d" $webService $webPort | quote }}
