apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trento-wanda.fullname" . }}-secret
type: Opaque
data:
  SECRET_KEY_BASE: {{ include "trento-wanda.secretKeyBase" . | quote }}
  ACCESS_TOKEN_ENC_SECRET: {{ include "trento-wanda.accessTokenSecret" . | quote }}