{{- /*
 SPDX-FileCopyrightText: SUSE LLC
 SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trento-wanda.fullname" . }}-secret
type: Opaque
data:
  SECRET_KEY_BASE: {{ include "trento-wanda.secretKeyBase" . | quote }}
