apiVersion: v1
kind: Service
metadata:
  name: {{ include "trento-wanda.fullname" . }}
  labels: {{- include "trento-wanda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ template "trentoWanda.port" . }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "trento-wanda.selectorLabels" . | nindent 4 }}
