apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.mutatingWebhookName | default "cert-manager-webhook" }}
  labels:
    app: {{ include "trento-server.name" . }}
    chart: {{ include "trento-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
webhooks:
  - name: webhook.cert-manager.io
    clientConfig:
      service:
        name: {{ .Values.webhook.serviceName | default "cert-manager-webhook" }}
        namespace: {{ .Values.webhook.namespace | default "cert-manager" }}
        path: "/mutate"
      caBundle: {{ .Values.webhook.caBundle | default "" }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
