apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-tokens-secret
type: Opaque
data:
  ACCESS_TOKEN_ENC_SECRET: {{ include "trento-web.accessTokenSecret" . | quote }}
  REFRESH_TOKEN_ENC_SECRET: {{ include "trento-web.refreshTokenSecret" . | quote }}
