apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secret
type: Opaque
data:
  admin-user: {{ "admin" | b64enc | quote }}
  admin-password: {{ include "trento.grafana.password" . | quote }}