apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "trento-web.fullname" . }}-prune-events-cronjob
spec:
  schedule: "{{ .Values.pruneEventsCronjobSchedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            envFrom:
              - configMapRef:
                  name: {{ include "trento-web.fullname" . }}-configmap
              - secretRef:
                  name: {{ include "trento-web.fullname" . }}-secret
              - secretRef:
                  name: {{ .Release.Name }}-auth-tokens-secret
            args: ['eval', 'Trento.Release.prune_events(["--days", "{{ .Values.pruneEventsOlderThan }}"])']
          restartPolicy: OnFailure
