name: Continuous Integration
concurrency: ci-${{ github.ref }}
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  OBS_USER: ${{ secrets.OBS_USER }}
  OBS_PASS: ${{ secrets.OBS_PASS }}
  OBS_PROJECT: ${{ vars.OBS_PROJECT}}

jobs:
  test-helm-charts:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.4.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.13
      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
      - name: Lint
        run: ct lint --config=ct.yaml --lint-conf=helmlintconf.yaml --helm-lint-extra-args="--set prometheus.server.auth.type=none"

  gh-release-rolling:
    name: Chart rolling release on GitHub
    needs:
      - test-helm-charts
    # TODO: Remove `pull_request` trigger!!!!
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: ./.github/workflows/publish-oci.yaml
    with:
      branch: main
      prerelease: true
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}

  gh-release:
    name: Chart release on GitHub
    needs:
      - test-helm-charts
    if: ${{ github.event.release && github.ref != 'refs/tags/rolling' }}
    uses: ./.github/workflows/publish-oci.yaml
    with:
      branch: main
      prerelease: false
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}

  obs-commit-charts:
    needs: [test-helm-charts]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    container:
      image: ghcr.io/trento-project/continuous-delivery:main
      env:
        DEST_FOLDER: "/tmp/osc_project"
        FOLDER: packaging/suse
      options: -u 0:0
    strategy:
      matrix:
        charts: ["trento-server"]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1
        id: latest-tag
        with:
          semver_only: true
          initial_version: 0.0.1
      - name: Configure OSC
        # OSC credentials must be configured beforehand as the HOME variables cannot be changed from /github/home
        # that is used to run osc commands
        run: |
          mkdir -p $HOME/.config/osc
          cp /home/osc/.config/osc/oscrc $HOME/.config/osc
          /scripts/init_osc_creds.sh
      - name: Prepare .changes file
        # The .changes file is updated only in release creation. This current task should be improved
        # in order to add the current rolling release notes
        if: github.event_name == 'release'
        run: |
          PACKAGE_NAME=${{ matrix.charts }}-helm
          CHANGES_FILE=${{ matrix.charts }}.changes
          CHART_FOLDER=$FOLDER/${{ matrix.charts }}
          osc checkout $OBS_PROJECT $PACKAGE_NAME $CHANGES_FILE
          mv $CHANGES_FILE $CHART_FOLDER
          TAG=${{ steps.latest-tag.outputs.tag }}
          ./hack/gh_release_to_obs_changeset.py ${{ github.repository }} -a shap-staff@suse.de -t $TAG -f $CHART_FOLDER/$CHANGES_FILE
      - name: Commit on OBS
        run: |
          echo "Commiting ${{ matrix.charts }} for package ${{ matrix.charts }}-helm"
          OBS_PACKAGE=$OBS_PROJECT/${{ matrix.charts }}-helm
          osc checkout $OBS_PACKAGE -o $DEST_FOLDER
          cp -r packaging/suse/${{ matrix.charts }}/* $DEST_FOLDER
          cp -r charts/${{ matrix.charts }}/Chart.yaml $DEST_FOLDER
          cd $DEST_FOLDER
          make
          osc ar
          osc commit -m "GitHub Actions automated update to reference ${{ github.sha }}"
