name: Dependabot auto-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Continuous Integration

jobs:
  auto-merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Auto-merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@2aff7945b51a5755b63e8dc2461bd184ca708a26 # v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
          MERGE_METHOD: MERGE
