# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Publish OCI chart

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: main
        description: The branch to build and publish.
      prerelease:
        type: boolean
        default: false
        description: >-
          Whether the release is a pre-release. It's expected the
          pre-release tag to be the same over time, eg. it's moving
          target.

    secrets:
      gh_token:
        description: GitHub Personal Access Token to interact with GH API.
        required: true
      ssh_key:
        description: >-
          SSH key to be used for repository access. The key needs
          write permissions to the repository.
        required: true

jobs:
  build-and-push:
    name: Build chart and push to OCI registry
    runs-on: ubuntu-24.04
    steps:
      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.4.0

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Need the full history because of `helm-oci-charts-releaser`
          fetch-depth: 0
          ref: ${{ inputs.branch }}
          ssh-key: ${{ secrets.ssh_key }}

      # --- Bundling and OCI upload section ---

      - name: Package chart
        id: package
        run: |
          set -e
          outdir="$(realpath ./package)"
          echo "outdir=$outdir" >> "$GITHUB_OUTPUT"

          chart_version="$(helm show chart charts/trento-server | grep -E '^version:' | cut -d" " -f2)"
          echo "chart_version=${chart_version}" >> "$GITHUB_OUTPUT"

          helm package --dependency-update --destination "$outdir" charts/trento-server

      - name: Login to GHCR registry
        run: echo "${{ secrets.gh_token }}" | helm registry login -u trentobot --password-stdin ghcr.io

      - name: Upload OCI artifact
        run: helm push ${{ steps.package.outputs.outdir }}/*.tgz oci://ghcr.io/trento-project/helm-charts

      # --- GitHub release section ---

      - name: Delete rolling tag so it can be recreated
        if: inputs.prerelease
        run: |
          gh release delete rolling --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Create pre-releaese and upload artifact
        if: inputs.prerelease
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          token: "${{ secrets.gh_token }}"
          name: "Cutting Edge"
          tag_name: rolling
          prerelease: true
          generate_release_notes: true
          make_latest: false
          files: |
            ${{ steps.package.outputs.outdir }}/*.tgz

      - name: Release version check
        if: ${{ ! inputs.prerelease }}
        run: |
          if [ $(cat VERSION) != ${{ steps.package.outputs.chart_version }} ]; then
            echo "Version mismatch, can't proceed with the release"
            exit 1
          fi

      - name: Upload artifact to already created release
        if: ${{ ! inputs.prerelease }}
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          token: ${{ secrets.gh_token }}
          tag_name: ${{ steps.chart-releaser.outputs.chart_version }}
          files: |
            ${{ steps.package.outputs.outdir }}/*.tgz
