name: Release

on:
  push:
    branches:
      - main
    paths:
      - "VERSION"

concurrency: ${{ github.workflow }}

jobs:
  pre-release:
    name: Detect new version, draft release, update changelog
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.detect-version.outputs.current-version }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ssh-key: ${{ secrets.RELEASE_KEY }}

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect new version
        id: detect-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          create-tag: false
          version-command: |
            cat VERSION

      - name: Bump chart version
        run: |
          CURRENT_VERSION="${{ steps.detect-version.outputs.current-version }}"
          PREVIOUS_VERSION="${{ steps.detect-version.outputs.previous-version }}"
          CURRENT_VERSION_ESCAPED=$(printf '%s\n' "$CURRENT_VERSION" | sed -e 's/[\/.]/\\./g')
          PREVIOUS_VERSION_ESCAPED=$(printf '%s\n' "$PREVIOUS_VERSION" | sed -e 's/[\/.]/\\./g')
          sed -ri "s/(^version: )$PREVIOUS_VERSION_ESCAPED/\1$CURRENT_VERSION_ESCAPED/"  charts/trento-server/Chart.yaml
          sed -ri "s/(^\#\!BuildTag: trento\/trento-server:)$PREVIOUS_VERSION_ESCAPED/\1$CURRENT_VERSION_ESCAPED/"  charts/trento-server/Chart.yaml

      - name: Commit Chart.yaml
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: main
          commit_message: "Bump version from ${{ steps.detect-version.outputs.previous-version }} to ${{ steps.detect-version.outputs.current-version }}"

      - name: Draft release
        id: draft-release
        uses: release-drafter/release-drafter@v6
        with:
          publish: false
          version: ${{ steps.detect-version.outputs.current-version }}
          disable-autolabeler: true
          config-name: release_drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.draft-release.outputs.tag_name }}
          release-notes: ${{ steps.draft-release.outputs.body }}

      - name: Commit new changelog
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: main
          commit_message: "Automatically update CHANGELOG.md for release ${{ steps.detect-version.outputs.current-version }}"

  release:
    name: Tag and publish release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.publish-release.outputs.tag_name }}
    needs:
      - pre-release
    steps:
      - name: Publish release
        id: publish-release
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
          tag: ${{ needs.pre-release.outputs.version }}
          version: ${{ needs.pre-release.outputs.version }}
          disable-autolabeler: true
          config-name: release_drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  obs-sync:
#    name: Update obs packages
#    if: vars.OBS_ENABLED == 'true'
#    uses: ./.github/workflows/obs.yaml
#    needs:
#      - release
#    secrets: inherit
#    with:
#      update_changelog: true
#      obs_project: ${{ vars.OBS_PROJECT_STABLE }}
